# I/O
data_path: "/home/yzhang/research/mRNAdesigner_3/predictive_model/mRNA2expression/E.coli_proteins_value_2.csv"
out_dir: "/home/yzhang/research/mRNAdesigner_3/output/sft/"
log_dir: "/home/yzhang/research/mRNAdesigner_3/output/sft/exp_logs"
ckpt_path: "/home/yzhang/research/mRNAdesigner_3/output/ckpt_563000.pt"

# Model parameters
init_from: "resume"
meta_vocab_size: 69
block_size: 1024
n_layer: 12
n_head: 12
n_embd: 768
bias: False

# Learning parameters
epochs: 200
max_iters: 10000
eval_interval: 100
log_interval: 10
eval_iters: 20
eval_only: False
always_save_checkpoint: True

# Early stopping parameters
early_stopping_patience: 10
early_stopping_min_delta: 0.005

# Training config
gradient_accumulation_steps: 4
batch_size: 8

# AdamW optimizer settings
learning_rate: 3.0e-4
dropout: 0.0
weight_decay: 1.0e-1
beta1: 0.9
beta2: 0.95
grad_clip: 1.0

# Learning rate decay settings
decay_lr: True
warmup_iters: 500
lr_decay_iters: 8000
min_lr: 3.0e-5

# DDP settings
backend: nccl

# System
device: cuda
dtype: float32 